apiVersion: v1
kind: ConfigMap
metadata:
  name: devmind-logging configuration-config
  namespace: devmind-production
data:
  config.yaml: |
    logging configuration:
      enabled: true
      mode: enterprise
      security:
        encryption: AES-256
        compliance: SOC2
      performance:
        caching: redis-cluster
        scaling: auto
      monitoring:
        metrics: prometheus
        tracing: jaeger
        logging: elasticsearch