apiVersion: v1
kind: Service
metadata:
  name: devmind-container-registry
  namespace: devmind-production
  labels:
    app: devmind
    component: container-registry
spec:
  selector:
    app: devmind
    component: container-registry
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devmind-container-registry
  namespace: devmind-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devmind
      component: container-registry
  template:
    metadata:
      labels:
        app: devmind
        component: container-registry
    spec:
      containers:
      - name: container-registry
        image: devmind/container-registry:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: COMPONENT
          value: "Container Registry"

// INFRASTRUCTURE UPDATE: Container Registry
// Date: 2024-10-02
apiVersion: v1
kind: Service
metadata:
  name: devmind-container-registry
  namespace: devmind-production
  labels:
    app: devmind
    component: container-registry
spec:
  selector:
    app: devmind
    component: container-registry
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devmind-container-registry
  namespace: devmind-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devmind...


// INFRASTRUCTURE UPDATE: Container Registry
// Date: 2024-11-05
apiVersion: v1
kind: Service
metadata:
  name: devmind-container-registry
  namespace: devmind-production
  labels:
    app: devmind
    component: container-registry
spec:
  selector:
    app: devmind
    component: container-registry
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devmind-container-registry
  namespace: devmind-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devmind...
