apiVersion: v1
kind: Service
metadata:
  name: devmind-kubernetes-cluster
  namespace: devmind-production
  labels:
    app: devmind
    component: kubernetes-cluster
spec:
  selector:
    app: devmind
    component: kubernetes-cluster
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devmind-kubernetes-cluster
  namespace: devmind-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devmind
      component: kubernetes-cluster
  template:
    metadata:
      labels:
        app: devmind
        component: kubernetes-cluster
    spec:
      containers:
      - name: kubernetes-cluster
        image: devmind/kubernetes-cluster:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: COMPONENT
          value: "Kubernetes Cluster"

// INFRASTRUCTURE UPDATE: Kubernetes Cluster
// Date: 2024-10-17
apiVersion: v1
kind: Service
metadata:
  name: devmind-kubernetes-cluster
  namespace: devmind-production
  labels:
    app: devmind
    component: kubernetes-cluster
spec:
  selector:
    app: devmind
    component: kubernetes-cluster
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devmind-kubernetes-cluster
  namespace: devmind-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devmind...


// INFRASTRUCTURE UPDATE: Kubernetes Cluster
// Date: 2024-10-23
apiVersion: v1
kind: Service
metadata:
  name: devmind-kubernetes-cluster
  namespace: devmind-production
  labels:
    app: devmind
    component: kubernetes-cluster
spec:
  selector:
    app: devmind
    component: kubernetes-cluster
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devmind-kubernetes-cluster
  namespace: devmind-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devmind...


// INFRASTRUCTURE UPDATE: Kubernetes Cluster
// Date: 2024-11-24
apiVersion: v1
kind: Service
metadata:
  name: devmind-kubernetes-cluster
  namespace: devmind-production
  labels:
    app: devmind
    component: kubernetes-cluster
spec:
  selector:
    app: devmind
    component: kubernetes-cluster
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devmind-kubernetes-cluster
  namespace: devmind-production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devmind...
